### ISSUE TITLE
debian77 box is missing on vagrantcloud.com

### ISSUE THREAD

**Issue by rubo77** [box-cutter/debian-vm#12]
I used your image from https://atlas.hashicorp.com/box-cutter/boxes/debian77 in my Vagrantfile a lot, but now it is missing and I struggle how to get it back ;)

I searched my home/.vagrant.d folder but there is only the debian77-i386-disk1.vmdk file.

So on my local computer I can still create new vagrant boxes from that cached version, but I cannot deploy this on other mashines.

Why was it deleted? And How can I create the same box in my atlas account?

**Comment by rubo77** [comment]
I now used `bmorg/debian-wheezy-i386` instead and this seemed to work as well

**Comment by annawake** [comment]
The boxes are back under https://atlas.hashicorp.com/boxcutter
